### PR TITLE
Admin expert review role

### LINKED ISSUE #163: Adminstrator / Expert Reviewer role
this role can give a "expert reviewed" approval, which is visible and searchable

### PR DESCRIPTION
**Pull request by grimm**
Fixes #163 , but not ready yet.

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
I think we need to be consistent on our use of badges for review
awrvi 2016-04-29 15-19-28

Missing ability tests for the review actions

**Comment by grimm** [comment]
selection_010
selection_009

Badges should be consistent now.

**Comment by smacfarlane** [comment]
Sorry, second half of my comment got obscured by screenshots:  `Missing ability tests for the review actions`

Question:  Should badges be consistently blue, or should the reviewed badge be consistently green?   Also noticed we're using .label in some spots and .badge in others (those colors are consistent).  Call it good and talk about it next sprint?

**Comment by grimm** [comment]
Will wanted to revisit the badge/label color and style later.  
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
:shipit:

**Pull request merged**
