### PR TITLE
Add in logos

### LINKED ISSUE #166: add in logos
IARC
NSF
CRC logo (forwarded to basecamp)
UAF photo credit - Todd Paris

### PR DESCRIPTION
**Pull request by grimm**
Fixes #166 

The logo order needs to be confirmed and the placement of the photo credit.

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
Do we want to shrink/convert the images to be a consistent size?

**Comment by teknofire** [comment]
The css will limit the view of the logo to a fixed 100px height.  Which for most of the logos will only do a small amount of resizing

The crc-ui logo though should probably be sized down to be closer to that.  We should make sure to keep the original logo.  Make a new resized one with a different file name.

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by teknofire** [comment]
👍

**Comment by smacfarlane** [comment]
:shipit:

**Pull request merged**
