### PR TITLE
Direct to community show if only one search result #55

### LINKED ISSUE #55: As a user if a search for communities only returns one result it should redirect me to the community page

### PR DESCRIPTION
**Pull request by grimm**
Fixes #55

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi 
Ready for Review

**Comment by smacfarlane** [comment]
There should be a couple integration tests that test the behavior of single and multi-result searches.

**Comment by grimm** [comment]
@gina-alaska/awrvi Ready for review

**Comment by smacfarlane** [comment]
Looks like you committed a .png from the tests.

**Comment by grimm** [comment]
@gina-alaska/awrvi Ready for review.

**Comment by teknofire** [comment]
The search_params method should be in the communities controller not the application controller.

**Comment by grimm** [comment]
@gina-alaska/awrvi Ready for review.

**Comment by smacfarlane** [comment]
The `helper_method :search_params` should be  moved into the communities controller, since that's where the method lives now.

**Comment by smacfarlane** [comment]
:+1:

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
