### PR TITLE
View community via friendly url #4

### LINKED ISSUE #4: A guest should be able to view the community info & any public indices via a friendly URL on the search/browse interface.
A guest should be able to view the community info & any public indices via a friendly URL on the search/browse interface.

### PR DESCRIPTION
**Pull request by grimm**
Fixes #4

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi ready for review.

**Comment by smacfarlane** [comment]
Should we have a :uniq constraint on slug?   Other than that :question: , :+1:

**Comment by grimm** [comment]
Fixed.

**Comment by teknofire** [comment]
There should be an index for the slug field that is also unique.  You can see that in action if you do something like `rails generate migration add_slug_to_communities slug:string:uniq`

**Comment by grimm** [comment]
Fixed

**Comment by teknofire** [comment]
The changes that are happening to the schema file are very inconsistent.  I think we need to make sure that we run `rails db:migrate:reset` in order to make sure the schema is correct for the migrations that exist in the database.  Especially for these initial branches where we make logs of changes.

**Comment by grimm** [comment]
I did that when I pushed the new schema, but I don't think that there should be any issues with it now?

**Comment by teknofire** [comment]
ok, go ahead and merge

**Pull request merged**
