### PR TITLE
Create categories

### LINKED ISSUE #19: Create categories resource
This is a closure_tree that handles the categorization of the various parts for the indexes.  Each one should be able to calculate the index value by averaging the indexes from all the child indicator responses.

Category would either have child categories or if it's a leaf would have questions

### PR DESCRIPTION
**Pull request by smacfarlane**
closes #19 
Creates categories resource with closure_tree, sorted by sort_order.  

Is there anything else we can/should track at this point? 
example

### CODE REVIEW

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi Ready for review

**Comment by grimm** [comment]
Looks good :+1: 

I only had one question on how things are sorted in the index.  I modified the root node and it popped down to the bottom so I'm assuming that it is ordered by how it's been modified in the database?  I tested other items and they too moved to the bottom, so no sorting?

**Comment by smacfarlane** [comment]
@grimm I think in that case it doesn't matter.  The views are using the default ordering right now, which is going to cause the behavior you're seeing.  

There is a sort_order field that will be used, along with the depth of the category in the tree, to determine where it goes on the page.  Since we haven't really talked about the look of the app yet, I've not bothered to modify the views or controller.

**Comment by teknofire** [comment]
We should rename that sort order column to be position

**Comment by teknofire** [comment]
Also I'm gonna make the same statement I had with #43 about not committing empty files or files that have only comments like the coffee, stylesheet and helper files that get nothing added

**Pull request merged**
