### PR TITLE
Make awrvi index number larger

### LINKED ISSUE #161: Make AWRVI Index # font larger

### PR DESCRIPTION
**Pull request by grimm**
Fixes #161

### CODE REVIEW

**Comment by teknofire** [comment]
Please attach a screenshot

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

I swapped the completeness and the awrvi index bars to make the index more prominent but also because it's probably better.  The completeness bar is more related to the sub indices anyway.  

selection_004

**Comment by grimm** [comment]
selection_005

**Comment by teknofire** [comment]
I think the entire line label included should be the same size.

One additional idea I've been thinking about is not using a progress bar
for the completeness.  We would need to brainstorm some other way to
integrate that information in the dashboard view.
On Apr 29, 2016 10:27 AM, "Jason Grimes" notifications@github.com wrote:

[image: selection_005]
https://cloud.githubusercontent.com/assets/100140/14925673/ffb8e630-0df4-11e6-8d79-a4f749090365.png

**Comment by smacfarlane** [comment]
We're also using different terminology on each view:
- AWRVI Index
- AWRVI Vulnerability Index
- AWRVI Vulnerability Score

For the 'Recent Assessments' blocks,  what about new-lining and centering the value? 
ex:

```
AWRVI Vulnerability Score
   <big>0.25</big>
```

**Comment by grimm** [comment]
selection_006

selection_007

New version...

**Comment by grimm** [comment]
At the very least we should probably change the more recent assessments to say "Vulnerability Index" instead of "Vulnerability Score"?

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by teknofire** [comment]
👍 

I added a another issue to cover the fixing of the labeling that we can fix up in the next sprint #184

**Pull request merged**
