### PR TITLE
Update applicationrb to use alaska time #144

### LINKED ISSUE #144: update application.rb to use alaska timezone as the default
Currently dates being shown in the application are in UTC

### PR DESCRIPTION
**Pull request by grimm**
Fixes #144

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
`config.active_record.default_timezone = :local`   scares me.  I need to go read up on it, but my gut tells me that would cause active record to store db entries as local time in the database, not UTC.   

@teknofire  Please tell me I'm wrong

**Comment by grimm** [comment]
It's my understanding that this tells active record to convert the database timezone (UTC) into the local default timezone, but I could be wrong for sure.  :)

**Comment by smacfarlane** [comment]
I'll be the first to admit timezones confuse the hell out of me and there's a good chance I'm not fully groking the issue.

However, the more I read into this, the more I think this is not the right solution.   The server (app and db) timezones should always be set to UTC.  Database entries should always be stored in UTC.  

Time.zone.now with default application.rb reports time in UTC 
Time.zone.now with timezone set to Alaska reports Alaska time.  

This says to me that we'd only be making times look right for people in Alaska.

**Comment by teknofire** [comment]
Err yeah, don't use the `active_record.default_timezone`

We definately want that to be UTC

`config.time_zone = 'Alaska'` is the config option that should be set

see http://edgeguides.rubyonrails.org/configuring.html#configuring-rails-components

**Comment by grimm** [comment]
That's not how the documentation reads:

config.active_record.default_timezone determines whether to use Time.local (if set to :local) or Time.utc (if set to :utc) when pulling dates and times from the database. The default is :utc.

From this it sounds like just setting it to Alaska timezone will not convert UTC to Alaska time when pulled out of the database?  It doesn't appear to affect how the dates will be saved to the database just how they are pulled?

**Comment by teknofire** [comment]
Correct which means it's only going to configure time zone settings for activerecord.  We want to set the timezone stuff for all of rails which is done using `config.time_zone`

> config.time_zone sets the default time zone for the application and enables time zone awareness for Active Record.

**Comment by teknofire** [comment]
Also, while it doesn't say that it changes how activerecord saves the date, `Time.local` interpretes the passed in date/time information in the local timezone and ignores the set timezone for the date.

> local(*args) public
> Same as Time::gm, but interprets the values in the local time zone.

Also looking at https://github.com/rails/rails/blob/master/activerecord/lib/active_record/timestamp.rb#L121
it changes the how it fetches the time based for updating the timestamp field to using the local time instead of utc time.

**Comment by smacfarlane** [comment]
I still don't think we want to change time_zone.  Everything I'm running into says that we should be setting the zone based on the users request like:  

```around_filter :user_time_zone, :if => :current_user

def user_time_zone(&block)
  Time.use_zone(current_user.time_zone, &block)
end```

Not sure where time_zone comes from on current_user though, I haven't found that documentation.   

But the server time (and application time) should be UTC.  The behavior I saw from my testing indicated to me that setting time zone to Alaska would not actually fix our problems.

**Comment by smacfarlane** [comment]
Alright, after our offline conversation, I think I see why in this case we want to set `config.time_zone = 'Alaska'`.

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by teknofire** [comment]
:+1:

**Comment by smacfarlane** [comment]
:ship: :it:

**Comment by vlraymond** [comment]
cruise ship + italian flag?

**Comment by grimm** [comment]
A ship + abbreviation for Italy or it   :)

**Pull request merged**
