### PR TITLE
Add rails_12factor gem to development/production

### PR DESCRIPTION
**Pull request by smacfarlane**
This appears to help performance in Otto vms.

### CODE REVIEW

**Comment by teknofire** [comment]
I would probably rather see something like

```
# config/environments/development.rb
MyApp::Application.configure do
  config.logger = ActiveSupport::Logger.new("/path/outside/of/shared/folders")
end
```

mostly cause it really annoys me when running tasks and other things in development.

**Comment by teknofire** [comment]
That was lifted from https://sethvargo.com/faster-rails-development-with-vagrant/

**Comment by smacfarlane** [comment]
Good point.  Forgot about rake tasks.   I've moved development logs to /home/vagrant/development.log, and disabled test logs.   Tests run much faster now. 

@gina-alaska/awrvi ready for review

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
