### PR TITLE
Add awrvi index entry forms

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi  First pass at the form input. It's ugly as sin right now, but you can enter data.   Closes #69

### CODE REVIEW

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  ready for review

**Comment by grimm** [comment]
I'm getting an error on the tests:

```
Cliver::Dependency::NotFound: Could not find an executable ["phantomjs"] on your path.
    test/integration/indices_forms_test.rb:6:in `block in <class:IndicesFormsTest>'

bin/rails test test/integration/indices_forms_test.rb:4
```

Looks like I need to install phantomjs?

And an error when I try to open the form:

```
Showing /vagrant/app/views/indices/_form.html.haml where line #3 raised:

undefined method `name' for nil:NilClass
```

**Comment by grimm** [comment]
All issues fixed.  :+1:

**Comment by teknofire** [comment]
need to add some documentation on how to get setup with phantomjs for otto dev stuff

**Comment by teknofire** [comment]
woot, dev:setup task worked and was able to run all the tests!

:+1:

**Pull request merged**
