### PR TITLE
Update indicies show

### LINKED ISSUE #107: Update indices show action to use new page format.
Want to start getting it setup to handle the final layout 

Community name at the top
Progress-bars showing the index values.  
Various sidebar content depending on if the user is logged in or not and what permissions they have, etc...

### PR DESCRIPTION
**Pull request by smacfarlane**
Closes #107 This updates the Show action for an Index to look similar to provided graphs.

@gina-alaska/awrvi   Ready for comment.   I think there are still a number of things that could be tweaked, but it's a start.

### CODE REVIEW

**Comment by grimm** [comment]
Looks good!  :+1:

**Comment by teknofire** [comment]
Seems pretty good, although we should probably make sure to include some rounding for the index value display.

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi   Added in rounding of vulnerability values.  Also added actual values next to the category and subindex names.

**Comment by smacfarlane** [comment]
awrvi

**Comment by vlraymond** [comment]
Cool! My thoughts:
- Decimal rounding should be consistent (0.XX or 0.XXX).
- Completeness: can it show percent and (XX/27) as well to be consistent with previous AWRVI research.
- Adding "AWRVI" lots of places: perhaps "AWRVI Vulnerability Index", "AWRVI Index Summary"
- Date, do we want to include a date of completion? "Verison" of AWRVI?
- Grammar nazi: change to "sub-index"

Ok so next steps ideas:
Visual: I don't think the colors make sense. Having the bar change a "good" or "bad" color isn't automatically intelligible.
Narrative: a template 4 line narrative that auto-completes with the index findings... shall we?

**Comment by smacfarlane** [comment]
@vlraymond  I think I've addressed most of your points.  
- Decimals are rounded to 2 consistently now.
- Changed completeness to a fraction
- Added AWRVI in all the places
- Grammar Schooled the AWRVI Version
- Change separator between words and numbers to :  (not in screenshot)

I skipped the date of completion as there isn't a way to finalize reports yet. 
The colors are based on the gradients given to us, but limited to the three default colors.  We'll need to add our own styling to get that bit right so I'm going to hold on addressing this for now.

Not sure what you mean by narrative,  but it sounds like it may be something we'll want to add as a separate task to tackle.  

awrvi 2016-03-23 15-13-47

**Comment by teknofire** [comment]
Functionally I'm happy with this, we can tweak the looks in a separate issue later.

**Pull request merged**
