### PR TITLE
Add admin field to users

### LINKED ISSUE #73: Create admin_users flag on user to handle authorizations
Create an admin boolean field that defaults to false for users
- Don't allow non admins to set their own flag

### LINKED ISSUE #75: Add authorizations for communities to lock down to just the :read permissions
We can evaluate later if we need to add the ability to manage communities

### PR DESCRIPTION
**Pull request by smacfarlane**
closes #73 

Also closes #75.  This is because the :read, All had to be changed to ensure that the User abilities functioned correctly

### CODE REVIEW

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  ready for review

**Comment by teknofire** [comment]
So the ability file is setup but there are no `authorize_resource` calls in any of the controllers to make use of them

**Comment by teknofire** [comment]
I guess technically the #73 is just for adding the fields for being able to setup the authorizations, but #75 is definitely about locking down the community access.

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  Updated to address @teknofire concerns.  Ready for review

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
