### PR TITLE
Create choices

### LINKED ISSUE #39: Create choices resource
Each indicator needs 5 choices to choose from. 

A choice belongs to a category and should have the following fields:

index:decimal
description:text

### PR DESCRIPTION
**Pull request by smacfarlane**
This creates choices for indicators and seeds existing data into them. Closes #39

### CODE REVIEW

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  Ready for review

**Comment by grimm** [comment]
Are we going to convert all of the .erb files to .haml?

**Comment by teknofire** [comment]
probably should also remove the helper test as that doesn't exist any more with the remove of the empty files

**Comment by smacfarlane** [comment]
@grimm  Fixed!

**Comment by grimm** [comment]
:+1:

**Pull request merged**
