### PR TITLE
Added disclaimer to main page and footer.

### PR DESCRIPTION
**Pull request by grimm**
region capture 1
region capture 2

### CODE REVIEW

**Comment by grimm** [comment]
Ready for review

**Comment by vlraymond** [comment]
Thanks Jason. Can we change it to this, sorry I only thought of this after seeing your screenshot:

 Disclaimer: The Arctic Water Resource Vulnerabilities Index (AWRVI) was first published in 2008 (doi: <link>10.1007/s00267-008-9152-0</link>).  Our researchers have revisited the index and made updates, such as changes to input parameters, units, scaling, etc.  The web interface here is based on the updated version of AWRVI. The updated index is not yet published. We will provide a link to that publication once it is in press.

Also please make sure the "." goes after the parenthesis.

thank ye

**Comment by grimm** [comment]
region capture 3

**Comment by vlraymond** [comment]
nice!

**Comment by grimm** [comment]
All good to merge?

**Comment by vlraymond** [comment]
yes!

**Pull request merged**
