### PR TITLE
Add labels to dashboard sliders

### LINKED ISSUE #164: insert a 0 and 1 into dashboard slider
or more generally display the context for the user

### PR DESCRIPTION
**Pull request by grimm**
Fixes #164

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
https://github.com/gina-alaska/awrvi/issues/164#issuecomment-214528728

Commented on the issue, but referencing here so this doesn't get merged until we talk about it.

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by teknofire** [comment]
With some of these things that are UI changes it helps to capture screenshots so that @vlraymond can see what it would like to give feedback as well

**Comment by grimm** [comment]
awrvi-slider-labels

Sorry, np, here is a snapshot.  :D

**Comment by teknofire** [comment]
Also rather than adding the labels on each progress-bar having it show up just one like at the top of the list of items would be better.

**Comment by grimm** [comment]
new-dashboard

How is this?

**Comment by vlraymond** [comment]
Ah, thanks for the screenshots.
It's still a bit cluttered, even with labels on only one item.
Possible solutions:
- Can you try putting the labels, just once, but above everything? Like
  above "natural supply".
- increase spaces between indicator
- unbold "more vulnerable" "less vulnerable"

sorry, this is a tricky one. And I hate to bring it up but I must: part of
the confusion stems from the way colors work in the bars.

On Wed, Apr 27, 2016 at 2:31 PM, Jason Grimes notifications@github.com
wrote:

> [image: new-dashboard]
> https://cloud.githubusercontent.com/assets/100140/14870140/ad99bf12-0c84-11e6-9498-35f6d11026df.png
> 
> How is this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/170#issuecomment-215251151

## 

Project Manager
Geographic Information Network of Alaska
_a part of the Geophysical Institute at University of Alaska Fairbanks_

**Comment by grimm** [comment]
awrvi - google chrome_001

New version, changed format and the text style for the labels.  :)

**Comment by teknofire** [comment]
I think that looks much better, @vlraymond we tried to put the labels just at the top but it looked awkward with the way the label for the progress bars were just below it as well.

**Comment by grimm** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
Now that the text is on there, those bars seem backwards and confusing to me.  Maybe the same/similar thing to what @vlraymond has been seeing this whole time?    

The issue is for me bars should go less -> more (left -> right) as they fill up, but the text is backwards from that.  Could we try using opposite wording, if there is a good way to phrase it?

**Comment by grimm** [comment]
awrvi - google chrome_003
How is this?  We could also do "bad ... good", "worse...better", etc.

**Comment by teknofire** [comment]
Not sure if we should be making that sort of statement with this
application.  I think we need to go back to Andy and Paula and show them
the screenshots and get their opinions on the wording.

On Thu, Apr 28, 2016 at 11:18 AM, Jason Grimes notifications@github.com
wrote:

> [image: awrvi - google chrome_003]
> https://cloud.githubusercontent.com/assets/100140/14898386/e88c71ba-0d32-11e6-9f8c-a3f8fba5f5ef.png
> How is this?
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/170#issuecomment-215533749

## 

Will Fisher
UAF-GINA | 907-474-1182 | will@alaska.edu

**Comment by smacfarlane** [comment]
That makes more sense to me,  but I don't know if that's the right word.  Agree with @teknofire, we should get the PI's to choose the wording on that.

**Comment by vlraymond** [comment]
Hi all,
I agree that the spacing between sub-indicators, the placement (below) and
non-bold font looks great.

The colors and the bars when combined with the text are still confusing.

For example in Ivanhof Bay example, economic and cultural capacity have the
same color green, but different amounts of "more or less vulnerability".
The wording alone could explain the significance of the amount represented
in the bar.
- The colors seem arbitrary as opposed to meaningful - especially
  because they do not change in obvious ways.
- Would we be better off just having the bars as a single color?I know
    that probably un-does quite a bit of work you did already :/
  - The blue color for "completeness" is confusing as it doesn't fit
    into color spectrum of the dashboards. However it is close enough in hue
    that it could possibly? The user  begins to self-doubt.

Word choice ideas, we can run them by the PIs however I'll add to the
suggestion list:
1. vulnerable to resilient
2.  more or less resilient

On Thu, Apr 28, 2016 at 11:28 AM, Scott Macfarlane <notifications@github.com

> wrote:
> 
> That makes more sense to me, but I don't know if that's the right word.
> Agree with @teknofire https://github.com/teknofire, we should get the
> PI's to choose the wording on that.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/170#issuecomment-215536421

## 

Project Manager
Geographic Information Network of Alaska
_a part of the Geophysical Institute at University of Alaska Fairbanks_

**Comment by grimm** [comment]
The colors should probably follow the hue of a color wheel, which I think they do for the most part.  That would be red->orange->yellow->yellow-green->green.  The ones that are missing is yellow and the yellow-green which I don't think that bootstrap has by default.

**Comment by teknofire** [comment]
After doing the demo today I think having something like Highly Vulnerable on the left and Highly Resilient on the right would work

**Comment by grimm** [comment]
selection_008

Fixed labels...  
@gina-alaska/awrvi  Ready for review.

**Comment by smacfarlane** [comment]
:shipit:

**Pull request merged**
