### PR TITLE
adding rubocop and hooking into travis

### PR DESCRIPTION
**Pull request by teknofire**
@gina-alaska/awrvi Ready for review

this will fail because we have a lot of things that need to be cleaned up

### CODE REVIEW

**Comment by smacfarlane** [comment]
:+1: 

Probably should fix these up in a different branch,  but I'm going to put my thoughts down here for the errors

`Keep a blank line before and after private.`
I'm ambivalent on this one, but if I had to chose I'd disagree.  Rails default is the opposite of this so turning this check off would be in line with rails default.

`Inconsistent indentation detected.`
Opposite of above. I don't like rails default indentation for private methods, but that means we'd have to fix all auto-generated code. 

`Prefer the new style validations`
This should be fixed.

`Align the elements of a hash literal`
This one comes from a simple form  configuration.  We should just turn off all cops for this file.

**Comment by teknofire** [comment]
`Inconsistent indentation detected.`
`Align the elements of a hash literal`
`Keep a blank line before and after private.`
I was fine leaving these things as complaints as they are easily fixable using the rubocop auto-correct.

**Comment by teknofire** [comment]
@gina-alaska/awrvi any objections to me merging this as is or do we want to have more discussion about the items commented on above?

**Comment by grimm** [comment]
:+1:

**Comment by smacfarlane** [comment]
:shipit:   I'll start a branch for fixing the errors where we can have that conversation.

**Pull request merged**
