### PR TITLE
Rename AWRVI Dashboard to Vulnerability Assessment

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi  Please review.

Looking through the docs we've been given, I see the term 'Vulnerabilty Assessment' being used to describe what we've been calling the dashboard, which I think is a better and more accurate term.  This PR changes all references to `AWRVI Dashboard` to `Vulnerability Assessment`

### CODE REVIEW

**Comment by teknofire** [comment]
👍

**Comment by grimm** [comment]
I no longer see the sub-indices for an index, is this correct?

**Comment by smacfarlane** [comment]
@grimm In what context?    This was almost entirely string changes,  only one method and one filename were changed so it shouldn't have affected the indices.

**Comment by dayne** [comment]
Hold off on this right now.  

I will bring this up during the demonstration tomorrow.

By broadening the name to a larger context that might be useful but currently the implementation is showing the calculated AWRVI ... which has been called, for as long as I've known it, the AWRVI dashboard.

**Comment by grimm** [comment]
@smacfarlane It was something else, I think it was the AWRVI 2.0 changes to the database causes the sub-indices to not show up in the dashboard.  If I rebuild the database it's ok again.

**Comment by teknofire** [comment]
@dayne the latest documentation refers to these as vulnerabilty assesments, which is what prompted this change

**Comment by grimm** [comment]
:+1:

**Comment by dayne** [comment]
My point on wanting to hold off on this was to see how EPSCoR leadership received and thought about the direction this might take.

By renaming it from AWRVI Dashboard to Vulnerability Assessment you are broadening the presented context for the AWRVI Dashboard. 

After discussions yesterday I have a better feeling of what level of broader engagement the program might be interested in this tool.  Leaving me with this question for the team:

On the public facing side (haml materials): Should the rename have been from "AWRVI Dashboard" to "AWRVI Vulnerability Assessment" instead of the broader context of "Vulnerability Assessment"?

**Comment by teknofire** [comment]
Oh this is just renaming the parts that show up when viewing the indexes.
Our use of the word dashboard in these cases was very awkward for the
individual assessments, plus aligns better with their updated paper that we
are now using.  I think we should still refer to the overall application as
the awrvi dashboard.

**Comment by dayne** [comment]
Ok.  Thanks.

**Pull request merged**
