### PR TITLE
First pass at updated form layout

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi   First pass at the updated layout for the index form.   Looking for feedback on the general workflow before I spend more time trying to make it look nice.

### CODE REVIEW

**Comment by grimm** [comment]
Looks good, the only problems I had were things you probably haven't gotten to yet.  :+1:

**Comment by teknofire** [comment]
I think probably wrapping it in a container to force it fixed width into the middle of the page would improve the look and feel

**Comment by smacfarlane** [comment]
awrvi 2016-03-23 12-54-37

**Comment by vlraymond** [comment]
looks MacNice

**Pull request merged**
