### PR TITLE
Change the width of the main column if there is no sidebar

### LINKED ISSUE #123: Communities layout should be full-width if no sidebar

### PR DESCRIPTION
**Pull request by smacfarlane**
Closes #123 

@gina-alaska/awrvi   I wasn't happy with the initial implementation (commented out for comparison to the current iteration).  I'm not sure if the second try is any better though.  Looking for comments.

### CODE REVIEW

**Comment by teknofire** [comment]
What about this method?

**Comment by grimm** [comment]
This is hard to test as there are no permissions for creating communities?

**Comment by teknofire** [comment]
You can see the difference by looking at a community vs looking at the list of communities.

**Comment by grimm** [comment]
Looks good :+1:

**Pull request merged**
