### PR TITLE
Add badges to show completion progress

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi   This is a first pass at adding completion progress badges. 

There's no dynamic updating as a user works on a form, which I find more confusing than not having badges at all.  Do we want to go down the road of figuring out dynamic updates?

### CODE REVIEW

**Comment by smacfarlane** [comment]
awrvi 2016-04-27 08-48-34

**Comment by teknofire** [comment]
I think we should and it would just need to be a little bit of javascript code to handle that

**Comment by vlraymond** [comment]
looks slick

On Wed, Apr 27, 2016 at 2:06 PM, Will Fisher notifications@github.com
wrote:

> I think we should and it would just need to be a little bit of javascript
> code to handle that
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/175#issuecomment-215245583

## 

Project Manager
Geographic Information Network of Alaska
_a part of the Geophysical Institute at University of Alaska Fairbanks_

**Comment by teknofire** [comment]
The javascript to do this would look something like

```
total = $('#category_3 select').size()
selected = $('#category_3 select option[value!=""]').filter(':selected').size()
```

You'll need to add some data attributes to the badge to know what category dom id to look for and then add a listener to the form to listen for updates to the items

**Comment by teknofire** [comment]
is this ready for review?  or where there more changes needed?

**Comment by vlraymond** [comment]
Looked good to me last I saw it

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  Ready for review.

**Comment by grimm** [comment]
:+1:

**Pull request merged**
