### PR TITLE
Revamp landing page layout and content

### LINKED ISSUE #110: Clean up the welcome page

### PR DESCRIPTION
**Pull request by teknofire**
This adds the placeholder for #23

image

Waiting on #121 to get finished as this needs updated fields from there to properly filter displayed items.

closes #110

### CODE REVIEW

**Comment by teknofire** [comment]
@gina-alaska/awrvi ready for review

**Comment by grimm** [comment]
:+1:

**Comment by smacfarlane** [comment]
Quick thoughts: 
I think we need more whitespace between the sections, possibly with a divider.  
Recent Dashboards gets a little lost in there. Possibly centering would help?

index.awrvi_index (in mini index) isn't calculated when published, so we should be using index.vulnerability_index, or caching value in awrvi_index that when published.

**Comment by teknofire** [comment]
Oh didn't see there was another method that calculated that on the fly, I'll switch to using that

**Comment by teknofire** [comment]
cleaned up the spacing a little bit, don't want to tweak to much right now, as there will be some images that are being gather to use as a background for the first section.

**Comment by teknofire** [comment]
image

Updated screen shot

**Comment by smacfarlane** [comment]
That's a lot easier to read. I can see the search bar now :stuck_out_tongue: 

:+1:

**Comment by grimm** [comment]
:+1:

**Comment by vlraymond** [comment]
:>

**Comment by vlraymond** [comment]
proposed content:
Fresh water is one of our most critical resources. Being able to see the ‘big picture’ of the water that communities rely on is an important asset in the decision-making process. The Arctic Water Resource Vulnerabilities Index (AWRVI) was developed because:
-No index exists to assess resilience and vulnerability of people in the Arctic to changes in water resources.
-Freshwater is critical to the sustainability of people in the Arctic.
-People in the Arctic face uncertainty in their day-to-day lives due to environmental changes.
-The need for Arctic communities to determine their vulnerability to changes in freshwater resources is becoming more urgent.
-The Arctic is a unique environment with a challenging set of factors including remote communities with poorly developed infrastructure and high energy costs, a rapidly changing climate, and variable abundance of liquid water much of the year. 

AWRVI provides a holistic profile of a community’s key water issues. It is designed to be used specifically in the Arctic’s varied and unique environment. The tool is a composite water index to evaluate the well-being of Arctic communities with respect to fresh water and a tool comprised of 27 socio-economic (e.g., social network capacity), biological (e.g., subsistence habitat) and physical (e.g. variation in precipitation) indicators.

**Pull request merged**
