### PR TITLE
Add cancancan

### LINKED ISSUE #61: Add cancancan to start setting up authorization

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi Initial PR with cancancan added and everyone-can-do-everything access.

It looks like there are some PR in cancancan about [Rails 5](https://github.com/CanCanCommunity/cancancan/pull/289)  so we may want to hold on pulling this in right away. 

Closes #61

### CODE REVIEW

**Comment by grimm** [comment]
Need to add Fixes #61 to the request, then waffle handles it better.

**Comment by smacfarlane** [comment]
Thanks @grimm.  Always forget that :disappointed:

**Comment by grimm** [comment]
:+1:

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
