### PR TITLE
User management

### LINKED ISSUE #7: A user should be able to access a profile page for themselves.
A user should be able to access a profile page for themselves.

### LINKED ISSUE #72: Create admin interface for user resource
This needs to include the list of the users
Show and edit and for a user.

If a user is not an admin_user don't allow them to edit other users
Don't allow a non admin user to make themselves an admin_user

### LINKED ISSUE #83: An admin should be able to set permission on users
We'll need to coordinate this to work with the devise system.  

Probably some sort of namespace user controller.

### PR DESCRIPTION
**Pull request by smacfarlane**
@gina-alaska/awrvi  First pass at user management.  I've ended up having to bake in a couple features(below).  Right now the views are horrible placeholders.  Do we want to clean those up before this gets merged, or make those separate issues?

closes #72 
closes #7 
closes #83

### CODE REVIEW

**Comment by teknofire** [comment]
did you run into the rails 5 friendly_id issue?

**Comment by smacfarlane** [comment]
Yes,  but adding the 'fix' in causes a number of tests to start failing and I haven't investigate yet.

**Comment by smacfarlane** [comment]
It looks like ClosureTree hasn't been updated to handle the new Rails 5 default of belong_to_required_by_default,  so I'm leave it at the Rails 4 default behavior.

**Comment by smacfarlane** [comment]
@gina-alaska/awrvi  I think this is ready for review,  unless we want to make the views created prettier.

**Comment by grimm** [comment]
Looks good, the only things I can see that you might want to do is to add in a user menu and a method in the dev rake task to set the user_admin flag?

**Comment by grimm** [comment]
I'm also getting a test error:

Failure:
AbilityTest#test_users_can_only_read_themselves:
User can read other users

bin/rails test test/models/ability_test.rb:9

Setup issue?

**Comment by smacfarlane** [comment]
@grimm  That's a transient error we've been seeing off and on.  Those tests have been in for a while and I'm not able to consistently repeat the failure, even with the same seed.

**Comment by grimm** [comment]
Interesting, I was wondering why travis worked and I got the error.

**Comment by smacfarlane** [comment]
@grimm  There's a 'profile' link in the navbar for users, and a manage->users link in the navbar for admins.

**Comment by grimm** [comment]
I see them now, thanks. :)

**Comment by grimm** [comment]
Looks good to me, except for the rubocop errors.  I was using something like user.user_admin ^= true and I guess you can use user.user_admin.! as well?

:+1:

**Comment by grimm** [comment]
Oops your rake task reports the opposite of what the user_admin is set to.

**Comment by smacfarlane** [comment]
Yeah, I used to have set/print in the opposite order and forgot to change it.  Should be fixed now.

**Comment by grimm** [comment]
:+1:  :+1:

**Comment by teknofire** [comment]
:shipit:

**Pull request merged**
