### PR TITLE
Add permission denied handling

### LINKED ISSUE #92: Handle permission denied errors
CanCanCan permission denied errors need to be handled so that they either log the user in, or redirect them with flash error.

### PR DESCRIPTION
**Pull request by teknofire**
It wasn’t showing the permission denied flashes correctly.

Also incorrect css to handle the sizing

closes #92

### CODE REVIEW

**Comment by teknofire** [comment]
@gina-alaska/awrvi ready for review

**Comment by smacfarlane** [comment]
We should probably add the tests back in to ensure models can be :managed by a user when logged in.

**Comment by teknofire** [comment]
So I'm not very happy with the way we are testing for permissions from the controller side of things right now.  In fact most of what is currently being done in the users and community controllers test related to permissions should just be in the abilities tests.  

Then there should be generic testing for how the system behaves when a permission problem is encountered from the general scenarios.  

Then the controller tests only have to be concerned with handling their actual jobs and not the permissions around their jobs.

I had started going down that route but quickly ran into a rabbit hole dealing with our current implementation of devise and setting up generic set of permission denied workflow testing.  Which may require us to rethink how we are handling some of that.  So I decided to leave that for a separate issue.

**Comment by teknofire** [comment]
See #119

**Comment by smacfarlane** [comment]
Yes. I would agree with that wall of text.  Until that's fixed though, is it worth adding the 'happy path' testing in?

**Comment by teknofire** [comment]
Guess I'm not sure what the happy path test is?  Are you referring to what
would be the normal tests for communities?

On Thu, Mar 17, 2016 at 9:13 AM, Scott Macfarlane notifications@github.com
wrote:

> Yes. I would agree with that wall of text. Until that's fixed though, is
> it worth adding the 'happy path' testing in?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/118#issuecomment-197979774

## 

Will Fisher
UAF-GINA | 907-474-1182 | will@alaska.edu

**Comment by smacfarlane** [comment]
Happy path isn't the right phrase, but I'm not getting enough caffeine today.  The controller tests right now assert that a not logged in user gets redirected.    That should be flipped to test that a logged in user actually can make those changes so we're testing what the controller is supposed to do ( like you said ).

**Comment by teknofire** [comment]
The user controller tests does have that.  For both admin and normal users

On Thu, Mar 17, 2016 at 12:05 PM, Scott Macfarlane <notifications@github.com

> wrote:
> 
> Happy path isn't the right phrase, but I'm not getting enough caffeine
> today. The controller tests right now assert that a not logged in user gets
> redirected. That should be flipped to test that a logged in user actually
> can make those changes so we're testing what the controller is supposed to
> do ( like you said ).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/118#issuecomment-198060395

## 

Will Fisher
UAF-GINA | 907-474-1182 | will@alaska.edu

**Comment by smacfarlane** [comment]
But the communities controller tests are all assert_redirected_to, which isn't the behavior we want, is it?

**Comment by teknofire** [comment]
currently that's all that the controller does for communities, we need to make a new issue to add permission for handling management of communities.

**Comment by grimm** [comment]
Looks good :+1: 
Although I wasn't able figure out how to test it to the point where I would get the "you are not allowed" error.  Anyway of forcing it to not auto log me in?

**Comment by teknofire** [comment]
you would just need to remove permissions to do the action from your user

**Comment by grimm** [comment]
Testing is good now, looks good.  :+1:

**Comment by smacfarlane** [comment]
Maybe make the `session[:referred_from_url] || request.referer || root_url` a protected method to clean it up a bit? 

Also, the redirect to gina::id  is going to break the developer auth,  which I use sometimes.  Do we want to fix the redirect to a 'Choose your login' page?

**Comment by teknofire** [comment]
Yeah, I was trying to decide if it was necessary or not to make that a
separate method.  I decided to leave it as is because right now nothing
else does the same thing and it wasn't overly complicated logic.

The redirect item I moved to a separate issue to tackle after this got
merged as it will need to have some new stuff added back in or a change in
how we want to handle the "local" account settings that are still active.

On Mon, Mar 21, 2016 at 4:27 PM, Scott Macfarlane notifications@github.com
wrote:

> Maybe make the session[:referred_from_url] || request.referer || root_url
> a protected method to clean it up a bit?
> 
> Also, the redirect to gina::id is going to break the developer auth, which
> I use sometimes. Do we want to fix the redirect to a 'Choose your login'
> page?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gina-alaska/awrvi/pull/118#issuecomment-199556100

## 

Will Fisher
UAF-GINA | 907-474-1182 | will@alaska.edu

**Comment by smacfarlane** [comment]
:+1:

**Pull request merged**
