### PR TITLE
Restrict ability of creation and editing of indicies

### LINKED ISSUE #76: Basic authorization for index
Only the user that entered it should be able to edit the index

Otherwise all users should be able to read indexes
Logged in users should be able to create indexes

### PR DESCRIPTION
**Pull request by smacfarlane**
closes #76  @gina-alaska/awrvi  Ready for review.

### CODE REVIEW

**Comment by grimm** [comment]
I was able to create an index and edit an existing index while logged out.  Unless this is not part of the issue?

**Comment by teknofire** [comment]
Ah, yes still has the skip authorization check in the controller

**Comment by smacfarlane** [comment]
Yup, I forgot the authorize_resource.  Fix incoming

**Comment by grimm** [comment]
:+1:

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
