### PR TITLE
Setup association between user and index.

### LINKED ISSUE #62: indicies should belong to a user

### PR DESCRIPTION
**Pull request by grimm**
Fixes #62

### CODE REVIEW

**Comment by grimm** [comment]
@gina-alaska/awrvi Ready for review.

**Comment by smacfarlane** [comment]
Do we want indices to always belong_to a user?  Can we have orphaned indices?

**Comment by teknofire** [comment]
Well, potentially if the user wants to delete their account, don't want to delete the index as well.

**Comment by smacfarlane** [comment]
:+1:

**Comment by smacfarlane** [comment]
I think this is missing a migration adding 'references:user' to Index

**Comment by smacfarlane** [comment]
:+1:

**Comment by teknofire** [comment]
:+1:

**Pull request merged**
